apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: gokulr03/app1:latest
        ports:
        - containerPort: 8000

